# Generated by Django 3.2.10 on 2022-01-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0003_auto_20211218_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_updated_category',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
