# Generated by Django 3.2.10 on 2022-01-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0005_auto_20220112_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowlistforskilnote',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
