# Generated by Django 3.2.8 on 2022-01-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0007_allowlistforskilnote_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowlistforskilnote',
            old_name='user',
            new_name='note_owner',
        ),
    ]
