# Generated by Django 3.2.8 on 2022-01-14 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wm', '0006_allowlistforskilnote_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowlistforskilnote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
