# Generated by Django 3.2.8 on 2022-01-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0009_remove_allowlistforskilnote_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowlistforskilnote',
            name='end_at',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='allowlistforskilnote',
            name='message',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='allowlistforskilnote',
            name='start_at',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='allowlistforskilnote',
            name='task',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
