# Generated by Django 3.2.8 on 2022-01-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0010_auto_20220115_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowlistforskilnote',
            name='order',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
