# Generated by Django 3.2.10 on 2022-01-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshortcut',
            name='team_member',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
