# Generated by Django 3.2.10 on 2022-01-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0002_myshortcut_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshortcut',
            name='page_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
