# Generated by Django 3.2.7 on 2021-09-24 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github',
            new_name='github1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='site1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='site2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='site3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='site4',
        ),
        migrations.AddField(
            model_name='profile',
            name='github2',
            field=models.CharField(default='www.github.com', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='github3',
            field=models.CharField(default='www.github.com', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='github4',
            field=models.CharField(default='www.github.com', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_original',
            field=models.CharField(default='www.github.com', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_updated_category',
            field=models.CharField(default='ca1', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='lecture_url',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='HistoryForUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
