# Generated by Django 3.2.8 on 2022-01-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0004_alter_profile_last_updated_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
