# Generated by Django 3.2.10 on 2022-01-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0003_myshortcut_page_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowListForSkilNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('member', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
