# Generated by Django 3.2.10 on 2022-01-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0004_allowlistforskilnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowlistforskilnote',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='allowlistforskilnote',
            name='role',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
