# Generated by Django 3.2.10 on 2022-01-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0007_alter_profile_github4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github1',
            field=models.CharField(blank=True, default='www.github.com', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github2',
            field=models.CharField(blank=True, default='www.github.com', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github3',
            field=models.CharField(blank=True, default='www.github.com', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github4',
            field=models.CharField(default='www.github.com', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_original',
            field=models.CharField(blank=True, default='www.github.com', max_length=20, null=True),
        ),
    ]
